- name: ping the server
  host: frontend
  tasks:
  - name: install nginx
    ansible.builtin.ping:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.ping:
      name: nginx
      state: started
      enable: yes

  

