- name: play level  variables
  hosts: local
  connection: local
  vars:
   COURSE: AWS
   DURATION: 10HRS
   TRAINER: sivakumarreddy
  tasks:
  - name: satrt the course
    ansible.builtin.debug:
    msg: "course name is: {{ COUTRSE }}, duration: {{ DURATION }}, trainer: {{ TRAINER }}"



