- name: play level variables
  hosts: localhost
  connection: local

  vars:
    course: Ansible
    duration: 5hr
    trainer: madhu

  tasks:
    - name: print the course details
      ansible.builtin.debug:
        msg: "course name is {{ course }}, duration: {{ duration }}, trainer: {{ trainer }}" 