- name: play level variabes
  hosts: local
  connection: local
  vars:
   course: Ansible
   duration: 5hr
   Trainer: madhu
  tasks:
  - name: prtint the course details
    ansible.builtin.debug:
    msg: "course name is {{ course }},duration:{{ duration }}, trainer:{{ trainer }}"

  