- name: play with variables
  hosts: localhost
  connection: local

  vars:
    course: github & git bash
    duration: 2hr
    Trainer: sivakumar reddy
  tasks:
  - name: print the course details
    vars:
      course: aws
    ansible.builtin.debug:
        msg: "course name is: {{ course }}, duration:{{ duration }}, Trainer:{{ Trainer}}"  
      
